# -*- mode: ruby -*-
# vi: set ft=ruby :

boxes = {
  "ie6"  => "http://aka.ms/vagrant-xp-ie6",
  "ie7"  => "http://aka.ms/ie7.vista.vagrant",
  "ie8"  => "http://aka.ms/ie8.win7.vagrant",
  "ie9"  => "http://aka.ms/ie9.win7.vagrant",
  "ie10" => "http://aka.ms/ie10.win8.vagrant",
  "ie11" => "http://aka.ms/ie11.win81.vagrant",
  "msedge" => "http://aka.ms/msedge.win10.vagrant",
}
box = File.basename(Dir.getwd)
remote_url = boxes[box]
local_path = box + '.box'
box_url = File.file?(local_path) ? local_path : remote_url

Vagrant.configure("2") do |config|
  config.vm.box = box
  config.vm.box_url = box_url
  config.vm.guest = :windows
  config.vm.hostname = "#{`hostname`[0..-2]}".sub(/\..*$/,'') + box
  config.vm.communicator = "winrm"
  config.winrm.username = "IEUser"
  config.winrm.password = "Passw0rd!"
  config.vm.provider "virtualbox" do |vm|
    vm.gui = true
    vb.customize ["modifyvm", :id, "--vram", "256"]
    vm.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
    vm.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    vm.customize ["guestproperty", "set", :id, "/VirtualBox/GuestAdd/VBoxService/--timesync-set-threshold", 10000]
  end
end
